### ISSUE TITLE
Question: Support microfrontend deployed on independent server?

### ISSUE THREAD

**Issue by joyfulelement** [onerzafer/micro-fe-registry#4]
Hi, I was deeply inspired by your article about [Understanding Micro Frontends
](https://hackernoon.com/understanding-micro-frontends-b1c11585a297) and was curious to know your thoughts about the question on serving microfrontends that are deployed on different servers.

### Assumption

Please correct me if I have misunderstood the role of microfe registry server: 

- It requires the built artefact from each independent microfrontend to be included on the same server, so it will help serve them.

### Questions

- If a particular SPA doesn't require server-side rendering, can microfe registry server be configured to simply serves the static content?
- What if each independent microfrontends are deployed on different server? 
    - Could we use [microfe-client](https://github.com/onerzafer/microfe-client) to help stitching them together on client side? Or
    - Having microfe registry server setup as a proxy server to fetch different microfrontend artefact dynamically from independent content server?

Presumably these may not be the target use case of this project, but I would be grateful if you could share your thoughts on them, many thanks!

**Comment by onerzafer** [comment]
Thanks @joyfulelement 
What you are asking and describing is the ultimate goal of this project. On the current state of this project, your assumptions are correct.

Regarding your question, I'm working on it at the moment :) Soon I am planning to merge the [new-architecture](https://github.com/onerzafer/microfe/tree/new-architecture) when it is more stable. On this branch, I'm aiming to solve CSR and SSR, dedicated servers for each micro-app (MicroAppServer) the problem is client-side routing and server-side routing.

**Comment by joyfulelement** [comment]
Thanks @onerzafer for the clarifications and confirmation about the assumption. I'll close this case now and look forward seeing the evolution of your approach for microfrontend, it's a really amazing work you're doing and thanks for sharing!
